### PR TITLE
[WIP] Upload all artifacts produced by Gradle, not just main ones

### PR DESCRIPTION
**Pull request by grv87**
Gradle 5.0 added built-in support for signing Maven and Ivy publications.
However, Artifactory plugin for Gradle doesn't upload produced signatures (*.asc) to Artifactory.
This PR fixes this.

### CODE REVIEW

**Comment by eyalbe4** [comment]
@grv87 - thanks so much for this contribution!
Would you mind resolving the conflicts so that we can merge this?

**Comment by grv87** [comment]
@eyalbe4, I've rebased, but still testing. Please, don't merge yet.

Also, with #228 additions I have two concerns:
1. I'm not sure, maybe there is better (more clean/simpler) way to set both `dependsOn` and list of files.
2. IIUC, Gradle < 4.8 became not supported.
If so, I'm gonna remove dynamic choice of methods with reflection.

**Comment by yahavi** [comment]
Thanks, @grv87.
Does this [PR](https://github.com/jfrog/build-info/pull/265) resolve this issue?

**Comment by yahavi** [comment]
@grv87 
I checked with https://github.com/jfrog/build-info/pull/265 and looks like the issue resolved. Tested with [Gradle signing plugin](https://docs.gradle.org/current/userguide/signing_plugin.html) and the following configuration:
```
signing {
    sign publishing.publications.mavenJava
}
```

All `.asc` files had been uploaded.

To check the snapshot use the following configuration:
```
buildscript {
    repositories {
        maven { url "https://oss.jfrog.org/oss-snapshot-local" }
        jcenter()
    }
    dependencies {
        classpath(group: 'org.jfrog.buildinfo', name: 'build-info-extractor-gradle', version: '4.9.x-SNAPSHOT')
    }
}
```

We'd appreciate your feedback for that!

**Pull request closed without merging**
