### PR TITLE
Making a distribute task

### PR DESCRIPTION
**Pull request by ethankhall**
This will allow users to add a distribute task to their builds.

I would love to add some testing, but I don't know how to do that here... Any suggestions?

### CODE REVIEW

**Comment by radai-rosenblatt** [comment]
hi JFrog developers.
any news on this?

**Comment by eyalbe4** [comment]
@ethankhall, 
My apologies for not replying on this PR for such a long time...I think we started debating internally back then about the best approach to allow this and the discussion was left open back then.
Quick question though - does this PR include all the code needed for the new suggested task? Does this work on your end? If so, can you please share a project example?
Thanks!

**Comment by ethankhall** [comment]
Yes. This was taken from multiple repos:

https://github.com/linkedin/dexmaker/blob/master/buildSrc/
https://github.com/linkedin/cruise-control/tree/master/buildSrc/

**Comment by eyalbe4** [comment]
@ethankhall,
Is there a build.gradle with the DSL for this new gradle task? Something that can be used to test and evaluate the new task in this PR?

**Comment by ethankhall** [comment]
Yep!

https://github.com/linkedin/cruise-control/blob/master/build.gradle#L364
https://github.com/linkedin/dexmaker/blob/master/build.gradle#L47

Since all the data comes from the JFrog plugin, we just need to create the task, and wire it up.

**Comment by eyalbe4** [comment]
@ethankhall,
Would it be possible to add an example project to the existing [gradle-examples](https://github.com/jfrog/project-examples/tree/master/gradle-examples) with the new distribution functionality?

**Comment by ethankhall** [comment]
@eyalbe4. I'm sorry no. It's been over 2 years since I've opened this. I'm not going to put any more effort into something that your team doesn't care about.

**Comment by eyalbe4** [comment]
@ethankhall,
I'd like to apologise again for the delayed responses relates to this contribution.
I really like the code and would really like to merge it. I'll take care of the additional work needed before releasing this functionality. No extra work needed from your side.  
I hope you're still okay with having the code merged.
In case you are, I'd like to ask you to kindly sign our [CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) 
We're not allowed to merge the code without it.
Thanks

**Comment by ethankhall** [comment]
@eyalbe4 thanks. I've signed the CLA.

**Comment by eyalbe4** [comment]
Thank you @ethankhall.
While looking into the code, I noticed that the new *DistributionTask* does not have a convention.
Since adding it required a lot of changes, I created a new PR - https://github.com/jfrog/build-info/pull/278 which based on your initial PR.
Let me know what you think. I think we can close this one.

**Comment by ethankhall** [comment]
I think it looks fine, but I don't have a way to verify it.

**Comment by eyalbe4** [comment]
@ethankhall,
The code in https://github.com/ethank code in https://github.com/jfrog/build-info/pull/278 will be included in the upcoming release, which is planned to be published by the end of the month. I think this PR can be therefore closed.

**Pull request closed without merging**
