### PR TITLE
Prevent 'Invalid cookie header' messages

### PR DESCRIPTION
**Pull request by rahulsom**
This is the kind of messages that end up in build logs when artifactory is fronted by an ALB

```
Invalid cookie header: "Set-Cookie: AWSALB=<Base64>; Expires=Wed, 22 May 2019 02:58:45 GMT; Path=/". Invalid 'expires' attribute: Wed, 22 May 2019 02:58:45 GMT
```

### CODE REVIEW

**Comment by rahulsom** [comment]
Before my change

```
Deploying artifact: https://artifactory.example.com/libs-snapshots-local/mygroup/myartifact/0.285.0-dev.0%2B8ccc085/myartifact-0.285.0-dev.0%2B8ccc085-sources.jar
Invalid cookie header: "Set-Cookie: AWSALB=jgFuoBrtnHLZCOr1B07ulLBEGSXLWcGZO8rTzzuuORNDpTubaDixX30r9N3F3Hy9xAlFgXhVghWJHE4V8uNQSNUsz7Wx7geQ8zrlG8mPva2yeCyuKDVm4iO6/IdP; Expires=Tue, 25 Jun 2019 22:20:19 GMT; Path=/". Invalid 'expires' attribute: Tue, 25 Jun 2019 22:20:19 GMT
Invalid cookie header: "Set-Cookie: AWSALB=NrRDEznq/R7AcdvcG9VOqnAy/Lfey8Vwxqpy3INBIFpkbsPed4EYBnXzo3DXhX3cZhDWe7yvg+D/LuVclShuIXU2CxLnAP/Fe245uFL9sWPMLBTFruu4asCkfJc2; Expires=Tue, 25 Jun 2019 22:20:19 GMT; Path=/". Invalid 'expires' attribute: Tue, 25 Jun 2019 22:20:19 GMT
Invalid cookie header: "Set-Cookie: AWSALB=PkQacELdTGj3PFcXy6x0JzyyJJTXWeDqXxmiQ41j9LUPV4nqAsmoc5Kn65bNldhhIjD5W3YWIihs7YdcBnZD4Fdb7UBolNE/OA+5iOCU/kZVHZyR8LkPlx5mjABl; Expires=Tue, 25 Jun 2019 22:20:19 GMT; Path=/". Invalid 'expires' attribute: Tue, 25 Jun 2019 22:20:19 GMT
Deploying artifact: https://artifactory.example.com/libs-snapshots-local/mygroup/myartifact/0.285.0-dev.0%2B8ccc085/myartifact-0.285.0-dev.0%2B8ccc085.jar
Invalid cookie header: "Set-Cookie: AWSALB=e/Zm20bwh+82hDLw9x2QwFNSfrK3s7DMv/u4l63IZjVkzC8oIL+ugmIAmfVzptFGSs3d3qfl1R4KHHpMPNynj926E+z9x8juA+x7BsQpUWpL/Uu7Gc+9P7ngexYY; Expires=Tue, 25 Jun 2019 22:20:20 GMT; Path=/". Invalid 'expires' attribute: Tue, 25 Jun 2019 22:20:20 GMT
Invalid cookie header: "Set-Cookie: AWSALB=mKf0fXjoQc9PA0zgIOlkkPRRVUQKmXUOX0gRzwqqAtntmvnvf6a7w42v3PUPN39d40eHkAfuqIHV71D16zo5nTPbG2/oHW57z9AcpF5zuyPM+4Mfoesoh84PCElP; Expires=Tue, 25 Jun 2019 22:20:20 GMT; Path=/". Invalid 'expires' attribute: Tue, 25 Jun 2019 22:20:20 GMT
Deploying artifact: https://artifactory.example.com/libs-snapshots-local/mygroup/myartifact/0.285.0-dev.0%2B8ccc085/myartifact-0.285.0-dev.0%2B8ccc085.zip
Invalid cookie header: "Set-Cookie: AWSALB=nqvE+Hp2+XMinbHXDw5f6d6bc+II+CpDYk8SfSX2S3Z9tJcTRvQ15ZA1kOVaT2cUTAhocpHq0G6pSJVMD/CFTzznV7d3ERx6hfLNSYURp3YBV75aUrULFuogcUq+; Expires=Tue, 25 Jun 2019 22:20:20 GMT; Path=/". Invalid 'expires' attribute: Tue, 25 Jun 2019 22:20:20 GMT
Invalid cookie header: "Set-Cookie: AWSALB=weHJy+rODL6rvtRzWMGZm0/BkSjOzo77azjUH3/Q2N0ooSxFCaj13M9PjoIhsb7pVIcM5QNFSFn058nezQnZGtF7bY6iAqvRgW3W6INCMXXDG1CP/F/wXHlU3Nv1; Expires=Tue, 25 Jun 2019 22:20:20 GMT; Path=/". Invalid 'expires' attribute: Tue, 25 Jun 2019 22:20:20 GMT
Deploying artifact: https://artifactory.example.com/libs-snapshots-local/mygroup/myartifact/0.285.0-dev.0%2B8ccc085/myartifact-0.285.0-dev.0%2B8ccc085-ivy.xml
Invalid cookie header: "Set-Cookie: AWSALB=fThX9pEgrWiXnNuocVwhniG0wH7VcYKnZMy4i6miElKBt5pkSaUe9MvwtSweAGAfl6j3M2W4A4UgEtvOnvhFzvwD4Ap+n424Y3TSBep/QZRSY6DkbJ4tB2t7r2pA; Expires=Tue, 25 Jun 2019 22:20:24 GMT; Path=/". Invalid 'expires' attribute: Tue, 25 Jun 2019 22:20:24 GMT
Invalid cookie header: "Set-Cookie: AWSALB=jG1k7jfP0NjP7n8iN3PkFGIAAjz58EHsRDk3JlJxhXPG1Bzz8dmM2hC+vjqjBfIpZZwYoMcrq9jLVH6p+CyDkGxAUmgXGUeau99HwgBa1Y5awgIvEJwEnBeF9TTV; Expires=Tue, 25 Jun 2019 22:20:26 GMT; Path=/". Invalid 'expires' attribute: Tue, 25 Jun 2019 22:20:26 GMT
Deploying build descriptor to: https://artifacts.example.com/api/build
Invalid cookie header: "Set-Cookie: AWSALB=gppIeEvGlJtcMLzPJsB7N5G45bo8vNTAQlfqQF/K4dyrTBV8MLp1559/PyHeG+I5mW11YQ8bNDx42IpR9MnIF8HDcORmPIhhmunSh9mGOp6GZRL2+42zq+gDUUxz; Expires=Tue, 25 Jun 2019 22:20:26 GMT; Path=/". Invalid 'expires' attribute: Tue, 25 Jun 2019 22:20:26 GMT
Build successfully deployed. Browse it in Artifactory under https://artifacts.example.com/webapp/builds/myartifact/1560896356091
```

After my change

```
Deploying artifact: https://artifactory.example.com/libs-snapshots-local/mygroup/myartifact/0.285.0-dev.0%2B8ccc085/myartifact-0.285.0-dev.0%2B8ccc085-sources.jar
Deploying artifact: https://artifactory.example.com/libs-snapshots-local/mygroup/myartifact/0.285.0-dev.0%2B8ccc085/myartifact-0.285.0-dev.0%2B8ccc085.jar
Deploying artifact: https://artifactory.example.com/libs-snapshots-local/mygroup/myartifact/0.285.0-dev.0%2B8ccc085/myartifact-0.285.0-dev.0%2B8ccc085.zip
Deploying artifact: https://artifactory.example.com/libs-snapshots-local/mygroup/myartifact/0.285.0-dev.0%2B8ccc085/myartifact-0.285.0-dev.0%2B8ccc085-ivy.xml
Deploying build descriptor to: https://artifacts.example.com/api/build
Build successfully deployed. Browse it in Artifactory under https://artifacts.example.com/webapp/builds/myartifact/1560896227734
```

**Comment by rahulsom** [comment]
@eyalbe4 Can you take a look at this when you get a chance? The log noise seems to scare my users more than it should.

**Comment by eyalbe4** [comment]
@rahulsom,
Did you try using the below API as described [here](https://stackoverflow.com/questions/36473478/fixing-httpclient-warning-invalid-expires-attribute-using-fluent-api/40697322)?
```
HttpClient httpClient = HttpClientBuilder.create()
            .setDefaultRequestConfig(RequestConfig.custom()
                    .setCookieSpec(CookieSpecs.STANDARD).build()).build();
```
It looks a lot shorter and simpler than the code you added.

**Comment by rahulsom** [comment]
Hi! @eyalbe4
There are multiple formats for cookies that depend on the reverse proxy, whether an AWS ALB is used, etc. For the fix to work, we need to handle all formats.
This fix is similar to the one in https://github.com/gradle/gradle/pull/2213.

**Comment by eyalbe4** [comment]
Thank you for this @rahulsom!
I pushed one commit on top of yours - https://github.com/jfrog/build-info/commit/364503a98cf924aa65886aab74c9caceda0ccde9 It only moves the code to a different method and added some documentation. Please have a look.
[BI-494](https://www.jfrog.com/jira/browse/BI-494) tracks this fix.

**Pull request merged**
