### PR TITLE
Non packaging pom project fails to deploy pom file to artifactory #91

### LINKED ISSUE #91: Non packaging pom project fails to deploy pom file to artifactory
We have a sub-module with our internal packaging type.
artifactory-maven-plugin 2.4.0 able to deploy pom file for sub-module non-pom packaging type.
But, it started failing to deploy pom file from 2.4.1 version.

I can see some code related to non packaging pom project module section modified from version 2.4.0 to 2.4.1
`build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
`

```
<artifactId>artifactory-maven-plugin</artifactId>
<groupId>org.jfrog.buildinfo</groupId>
```

### PR DESCRIPTION
**Pull request by chrislovsund**
Fixes #91

We are running the changes successfully in our production environment.
See also https://www.jfrog.com/jira/browse/NMAP-33

### CODE REVIEW

**Comment by aygalinc** [comment]
Hi, Have you some news on this PR ?

**Comment by chrislovsund** [comment]
I reminded in the JIRA. If you need the fix you can build the jar yourself like we did.

**Comment by eyalbe4** [comment]
@chrislovsund,
My apologies for not looking into this PR sooner. We'll review it soon.

**Comment by eyalbe4** [comment]
@chrislovsund,
Can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your code?

**Comment by chrislovsund** [comment]
@eyalbe4 No problem, done with signing.

**Comment by aygalinc** [comment]
Hi @eyalbe4 , do you plan any release that will contain this modification ?

**Pull request merged**
