### PR TITLE
Gradle Kotlin DSL Support

### PR DESCRIPTION
**Pull request by sugarmanz**
- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/build-info) passed. If this feature is not already covered by the tests, I added new tests.
-----

This is an attempt to solve for #184 and partially #269 to provide Gradle Kotlin DSL support for the Artifactory Gradle plugin. I added an integration test using the Kotlin DSL based on the publication integration test. If that isn't sufficient, I can convert the other integration test cases as well.

In terms of approach, I tried to simply convert all `Closure`s to `Action`s, but I ran into trouble supporting the Groovy DSL as well, so I just implemented `Closure` overloads that delegate to the `Action` implementations. Additionally, I wasn't able to figure out how to support the `DoubleDelegateWrapper` with `Action`s, so in those cases the Groovy DSL _might_ have more functionality than the Kotlin DSL. 

Please let me know if there is anything I can do to help get this reviewed!

### CODE REVIEW

**Comment by sugarmanz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sugarmanz** [comment]
recheckcla

**Comment by sugarmanz** [comment]
@yahavi @eyalbe4 @RobiNino tagging you because I see you as contributors/maintainers in #439. Can one of you please advise on how I can get this reviewed? Thanks.

**Comment by jfrog-aparicio** [comment]
Hello @sugarmanz. Thanks for the contribution. I will check with the team and get back to you.

**Comment by eyalbe4** [comment]
Thanks so much for this contribution @sugarmanz!
This functionality is definitely something we want to see as part of the gradle Artifactory Plugin. 
We're planning to start reviewing it soon.

**Comment by eyalbe4** [comment]
Thanks so much for thsi contribution @sugarmanz!
I reviewed the code, and I think it looks very good to me.
Before we go ahead and merge the code, will you be able to add an example project to https://github.com/jfrog/project-examples/tree/master/gradle-examples?
This should help us support and maintane the new functionality.
Thanks!

**Comment by sugarmanz** [comment]
Awesome! Appreciate the review. I'll add an example and post link the PR here when I'm done.

**Comment by sugarmanz** [comment]
Opened a PR for the project examples repo with a Gradle Kotlin DSL example:
https://github.com/jfrog/project-examples/pull/262

Let me know if you'd like more than one!

**Pull request merged**
