### PR TITLE
Fix for bug where broken data causes NullPointerException

### PR DESCRIPTION
**Pull request by johan-backstrom**
- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/build-info) passed. If this feature is not already covered by the tests, I added new tests.
-----

### CODE REVIEW

**Comment by johan-backstrom** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by johan-backstrom** [comment]
@eyalbe4 @yahavi  Is there a way to run the tests on your ci-server: https://ci.appveyor.com/project/jfrog-ecosystem/build-info

Or do I have to set up a test environment myself to run all tests?

**Comment by eyalbe4** [comment]
@johan-backstrom,
Thanks for this fix.
We're planning to add tests triggering for this project, but this hasn't been done yet. 
You'll need to set up your own Artifactory instance for now, and run the tests as described in the README. You can get a free JFrog Platform instance in the cloud. Please let me know if you need assistance with this.

**Review by RobiNino — APPROVED** [review]
I run the test on my env, LGTM!

**Comment by RobiNino** [comment]
Thanks for this fix @johan-backstrom !

**Comment by johan-backstrom** [comment]
No problem and thank you for the quick response!

**Comment by RobiNino** [comment]
Hi @johan-backstrom ,
Jenkins Artifactory Plugin version 3.10.4 is now released and includes this fix.
Thanks again!

**Pull request merged**
