### PR TITLE
Introduce support for kaniko docker images

### PR DESCRIPTION
**Pull request by cwholmes**
- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/build-info) passed. If this feature is not already covered by the tests, I added new tests.
-----

My team uses kaniko a lot for building docker images inside a kubernetes cluster (using the kubernetes-plugin). This currently requires adding dind as a container and pushing through the dind container after creating a tar with kaniko. We would like to avoid this by pushing with kaniko and creating the build info for the docker image.

This logic is somewhat replicating the `jfrog rt build-docker-create` command seen here:

https://github.com/jfrog/project-examples/tree/master/kaniko-example#kaniko-example

### CODE REVIEW

**Comment by cwholmes** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by cwholmes** [comment]
@eyalbe4 Could you please take a look at this change? My organization would really like to be able to support artifactory builds with kaniko. Thanks.

**Comment by eyalbe4** [comment]
Definitely @cwholmes!
Thanks so much for this contributions.
Give us just a few more days.

**Comment by yahavi** [comment]
@cwholmes,
Thanks for this contribution! 
We recently [changed](https://github.com/jfrog/build-info/pull/493) the Artifactory clients to services-style attitude. Basically, it replaces `ArtifactoryBuildInfoClient` and `ArtifactoryDependenciesClient` by `ArtifactoryManager` and removes the HTTP client requests and responses handling.

Therefore before merging your PR, we should merge from the master branch and migrate to the Artifactory manager. 
Would you like to pull the latest changes from the master branch?

You can use this as a reference to help you merging the BuildDockerCreate class: https://github.com/cwholmes/build-info/commit/1cd2fe670a00359e5d4adb1f7b3ba8926fa4f2ca

Please let us know if you encounter any difficulties.

**Comment by cwholmes** [comment]
@yahavi I have made the requested changes and used the artifactory manager.

**Comment by yahavi** [comment]
@cwholmes,
Thanks again for your contribution. We merged this PR to give you the credit and respect you're truly deserved.

I'd like to let you know that we elevated your PR to support both Kaniko and [JIB](https://github.com/GoogleContainerTools/jib).
We are working on follow-up PRs to add this support in the Jenkins Artifactory plugin:

* https://github.com/jfrog/build-info/pull/512 - this PR is a direct follow-up for your PR. It fixes fallen tests and adds support for JIB.
* https://github.com/jfrog/jenkins-artifactory-plugin/pull/503 - This PR introduces the Build Docker Create commands in the Jenkins Artifactory plugin. See usage in this PR.

We'd appreciate any feedback/review/thoughts before we merge the above PRs.

**Pull request merged**
